#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t ev"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.build.romversion`";
$L "Attempting to boot Lente by Nikez.";
$L "Please visit XDA for updates.";

